# Generated by Django 2.2.7 on 2019-11-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '类目表',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('img', models.CharField(max_length=200, verbose_name='图片')),
                ('style', models.CharField(max_length=20, verbose_name='样式')),
                ('time', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categroy', verbose_name='类目id')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(default='admin', max_length=20, verbose_name='密码')),
                ('name', models.CharField(default='abc', max_length=20, verbose_name='昵称')),
                ('reg_time', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('real', models.CharField(default='abc', max_length=20, verbose_name='真实姓名')),
                ('birth', models.CharField(default='1996-08-10', max_length=20, verbose_name='生日')),
                ('sex', models.CharField(default='男', max_length=20, verbose_name='性别')),
                ('address', models.CharField(default='太原', max_length=100, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20, verbose_name='库存')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Goods', verbose_name='商品id')),
            ],
            options={
                'verbose_name_plural': '库存表',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Shopcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=20, verbose_name='总价')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Goods', verbose_name='商品id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Users', verbose_name='用户id')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'db_table': 'shopcar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.CharField(max_length=20, verbose_name='订单号')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('pay', models.CharField(max_length=20, verbose_name='支付方式')),
                ('time', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Goodsvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('size', models.CharField(max_length=20, verbose_name='尺码')),
                ('price', models.CharField(max_length=20, verbose_name='价格')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Goods', verbose_name='商品id')),
            ],
            options={
                'verbose_name_plural': '商品属性表',
                'db_table': 'goodsvalue',
            },
        ),
        migrations.CreateModel(
            name='Categoryvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categroy', verbose_name='类目id')),
            ],
            options={
                'verbose_name_plural': '类目属性值表',
                'db_table': 'categoryvalue',
            },
        ),
        migrations.CreateModel(
            name='Categoryproperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='类目属性名')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categroy', verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '类目属性表',
                'db_table': 'categoryproperties',
            },
        ),
    ]
