# Generated by Django 2.2.7 on 2019-11-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvalue',
            name='name',
            field=models.CharField(default='无', max_length=20, verbose_name='类目属性值名'),
            preserve_default=False,
        ),
    ]
