# Generated by Django 2.2.7 on 2019-12-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191205_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='AttrChoice',
        ),
        migrations.RemoveField(
            model_name='page',
            name='attr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='goods',
        ),
    ]
